// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase env vars: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.",
  );
}

// Purge stale Supabase sessions if project changes (after const declarations)
try {
  const currentProject = new URL(SUPABASE_URL).hostname.split('.')[0];
  const staleKeys = Object.keys(localStorage).filter(
    (k) => k.startsWith('sb-') && !k.includes(currentProject)
  );
  staleKeys.forEach((k) => localStorage.removeItem(k));
} catch { /* SSR or localStorage unavailable */ }

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});